### ISSUE TITLE
Unable to use library because of Pydantic errors

### ISSUE THREAD

**Issue by kincl** [equinix-labs/metal-python#44]
I am getting an error when trying to import the library. I tried with both python 3.9 and 3.11

Am I doing something wrong here?

```
$ python -c 'import equinix_metal'
/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/Users/jkincl/work/equinix/openshift-install-assisted.py", line 4, in <module>
    import equinix_metal
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/__init__.py", line 23, in <module>
    from equinix_metal.api.authentication_api import AuthenticationApi
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/api/__init__.py", line 6, in <module>
    from equinix_metal.api.authentication_api import AuthenticationApi
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/api/authentication_api.py", line 27, in <module>
    from equinix_metal.models.auth_token import AuthToken
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/models/__init__.py", line 53, in <module>
    from equinix_metal.models.create_device_request import CreateDeviceRequest
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/models/create_device_request.py", line 24, in <module>
    from equinix_metal.models.device_create_in_facility_input import DeviceCreateInFacilityInput
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/models/device_create_in_facility_input.py", line 25, in <module>
    from equinix_metal.models.facility_input_facility import FacilityInputFacility
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/models/facility_input_facility.py", line 29, in <module>
    class FacilityInputFacility(BaseModel):
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/equinix_metal/models/facility_input_facility.py", line 39, in FacilityInputFacility
    any_of_schemas: List[str] = Field(FACILITYINPUTFACILITY_ANY_OF_SCHEMAS, const=True)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkincl/work/equinix/env/lib/python3.11/site-packages/pydantic/fields.py", line 749, in Field
    raise PydanticUserError('`const` is removed, use `Literal` instead', code='removed-kwargs')
pydantic.errors.PydanticUserError: `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.1.1/u/removed-kwargs
```

**Comment by ctreatma** [comment]
The behavior you're seeing may be related to this issue in the OpenAPI generator we're using: https://github.com/OpenAPITools/openapi-generator/pull/15189

The fix for that issue hasn't been included in a generator release yet, but in the meantime you could try installing pydantic < 2 and see if that resolves the error.

**Comment by kincl** [comment]
Ah thanks, that worked using:

```
pydantic==1.10.12
pydantic_core==2.4.0
```
